### ISSUE TITLE
Multiple confusing warnings and errors when exporting within WSL

### ISSUE THREAD

**Issue by fridde** [zim-desktop-wiki/zim-desktop-wiki#1064]
I am getting a lot of unnecessary warnings that sent me on a long quest to debug even though there was nothing to debug (it seems).

### My setup
I write my notes using the portable Win64 Zim desktop app v 0.69.1 (the newest that was available without rebuilding).
I export my notebook using Zim 0.72.1 from a shell within WSL (Ubuntu 18.04). I installed the ```.deb``` file given [on the downloads page ](https://zim-wiki.org/downloads/). 

### My problem
When running an export (or even just running ```zim --version```) I get this huge pile of errors/warnings (see below ) that seem irrelevant for my purposes. I neither want to run a server nor do I need a GUI when running Zim within my shell.

Is this intentional or am I missing something? Will I run into problems later on?

Btw, the export is successful and ```export.html``` looks as expected.

```
$> zim --export -o /mnt/d/temp/zim-exports/export.html -s --template ZeroFiveEight /notebook.zim --overwrite
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(zim:5450): Gdk-CRITICAL **: 18:38:08.945: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(zim:5450): Gdk-CRITICAL **: 18:38:08.945: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(zim:5450): Gdk-CRITICAL **: 18:38:08.946: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(zim:5450): Gtk-CRITICAL **: 18:38:08.946: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed
```

**Comment by heldergg** [comment]
I was going to report this bug. You're getting these errors because you do not have X installed on WSL (don't even know if that's possible). 

I get the same errors when I rebuild the index of a notebook on a headless server (the server gets the notebook from my desktop via a Seafile library). The index gets updated also so these errors aren't critical. 

Here's the full log I get:

[zim.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/4599781/zim.txt)

**Comment by introt** [comment]
> Btw, the export is successful

Then it's safe to ignore the gtk errors :)
