### ISSUE TITLE
Many issues with 0.73.1 Windows version

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1169]
There are unfortunately many issues with the new version on Windows:

- [ ] **The menu that comes up when right-clicking the Zim icon in the Windows taskbar will be empty, and one cannot quit Zim from there (or do anything else)**
![image](https://user-images.githubusercontent.com/2971539/87137943-f7b96d80-c29d-11ea-8379-5e909aa5c49d.png)

- [ ] **Most of the time, the Index pane does not show**
![image](https://user-images.githubusercontent.com/2971539/87138370-9940bf00-c29e-11ea-9927-969ea368f17d.png)

- [ ] **Sometimes, it does show randomly, but then there are no folder indicators (triangles?) in the Index pane**
![image](https://user-images.githubusercontent.com/2971539/87137860-d9537200-c29d-11ea-83ed-d657d812a0d7.png)

- [ ] **The task list does neither show any tasks, nor any tags or special keywords**
![image](https://user-images.githubusercontent.com/2971539/87137806-c93b9280-c29d-11ea-9ede-28620ea44245.png)

- [ ] **The task list properties cannot be saved ("Access is denied" error message when attempting to save settings)**
![image](https://user-images.githubusercontent.com/2971539/87137717-a4dfb600-c29d-11ea-80c3-f53d07255b1f.png)

- [ ] **Additional user plugins do not load (or at least don't show in the interface)**
      This might still be related to the bug from before, where plugins would only load when Zim is started in Debug Mode (cannot confirm, as there is no Debug Mode executable anymore in the new version)

**Comment by sergioflorespereira** [comment]
Hi,

Also having issues with the windows install ... I posted this link yesterday.

https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1157#issuecomment-656047020

Thanks.
Sergio

**Comment by jaap-karssenberg** [comment]
Sorry to hear you have many issues, but please do not post as a single
issue - need to be dealt with one by one.

REgards,

Jaap

**Comment by fdt-dev** [comment]
Comments on that: The menu popping up when right-clicking the task bar icon will become populated when the mouse is run up and down over it. That's still a bug. Expected behaviour would be that the menu is populated instantly.

The "triangles" in front of entries are invisible. But: clicking where the triangles should be expands the sub-level entries. Still: Expected behaviour would be: indicators for sub-level visible. In version 0.69 under Windows those were little squares with plus signs, but they could be triangles or whatever. :-)

**Comment by fladd** [comment]
Split into separate issues.
