### ISSUE TITLE
Windows 0.73.1: The task list does neither show any tasks, nor any tags or special keywords

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1195]
![image](https://user-images.githubusercontent.com/2971539/87137806-c93b9280-c29d-11ea-9ede-28620ea44245.png)

#1169

**Comment by fladd** [comment]
Update for 0.73.1: The task list shows tags, but not special keywords.

**Comment by fladd** [comment]
Some more information:

I use special keywords to track the state of a task:
![image](https://user-images.githubusercontent.com/2971539/89018425-287c4800-d31c-11ea-88c4-ca57256bd9d9.png)

While the tags show, the keywords do not:
![image](https://user-images.githubusercontent.com/2971539/89018859-c3752200-d31c-11ea-8c98-c3d2ca47e21f.png)


This was all fine in former versions (i.e. <0.73).

**Comment by jaap-karssenberg** [comment]
The idea was for labels to be some text followed by a ":" probably the
matching became a bit more strict in one of the intermediate versions,
because matching text without the ":" gave unintended matches.

Need to think whether that restriction makes sense for the generic case.

Using "A:" will work (after changing the properties to "A"), not sure
whether with the current setup "[A]:" works, but might well be.

-- Jaap

**Comment by fladd** [comment]
I now seem to have solved it by putting spaces after the commas in the list of keywords.

**Comment by fladd** [comment]
So this works now: [A], [W], [S]

**Comment by fladd** [comment]
Please don't remove matching for any keyword (even without : at the end)! This feature currently is great to properly implement a very flexible GTD system.

**Comment by jaap-karssenberg** [comment]
Ah - let me fix it such that the comma works as expected

**Comment by jaap-karssenberg** [comment]
Fixed parsing of labels in development branch
