### ISSUE TITLE
Search replaces text in new snapshot version

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1244]
If you have a formatted word and you search for a part of it, then its text gets replaced while searching. This is IMHO a critical bug, because it already accidentally altered the text of some of my notes.

To reproduce:

Write 2016 in bold, press enter for a new line, and search (ctrl+f) for 16 and be astonished :)

Happens with this version: 0.73.2-SNAPSHOT-t202008182001~ubuntu20.04.1

**Comment by nelas** [comment]
This happened to me as well while searching in a page full of formatted words (bold, italics, superscripts). I accidentally changed the text several times and had to be extra careful. It happens when the keyboard focus moves from the search box to the formatted word unexpectedly, ending up replacing the text while you are still typing the search term.

**Comment by jaap-karssenberg** [comment]
Cannot reproduce this. Can you be more specific under what circumstances
the focus changes unexpectedly?

-- Jaap

**Comment by sojusnik** [comment]
Did you try?

> Write 2016 in bold, press enter for a new line, and search (ctrl+f) for 16 and be astonished :)

It's important that your text consists of formatted words (bold, italic etc.).

**Comment by jaap-karssenberg** [comment]
Got it - the formatting of the word is crucial for reproducing

**Comment by jaap-karssenberg** [comment]
Fix pushed in develop branch
