### ISSUE TITLE
[Proposal] Tooltips for images

### ISSUE THREAD

**Issue by a-sennov** [zim-desktop-wiki/zim-desktop-wiki#1315]
Tooltips appear when you hover your mouse pointer over image for some time.

![2020-11-03_16-06-23](https://user-images.githubusercontent.com/3610734/97990514-19aca200-1df1-11eb-98d9-c9885c0dec31.png)
Tooltips display the relative path to image file as shown on picture above.

If image has link to another page, path to the page is appended to tooltip in boldface, see picture:
![2020-11-03_16-05-05](https://user-images.githubusercontent.com/3610734/97990704-65f7e200-1df1-11eb-9b7e-d7426aedfdfc.png)

I have this feature implemented, gonna submit PR and link it to this issue.

Current codebase has some mentions of image tooltips using 'alt' attributes, but this is not implemented. Moreover, I think that descriptive names for images are more straightforward way to organize them.

**Comment by pfalcon** [comment]
> Current codebase has some mentions of image tooltips using 'alt' attributes, but this is not implemented. Moreover, I think that descriptive names for images are more straightforward way to organize them.

Exactly, *descriptive* names, i.e. 'alt' attribute would be better than just showing path. Also note that for Markdown support, https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/26, it definitely would need to show "description" part from `![description](url)`.

Otherwise, tooltips sounds like a good idea, thanks for looking into it.

**Comment by a-sennov** [comment]
When 'alt' will make it into PageView data model then there will be time to display it :) I also doubt about usefulness of it as it's much faster to just drop image in place than edit description (in each single page that links to this image!)

For me, ability to see the origin of image is important especially when paired with drag and drop of images between pages, as you want to know what came from where (drag'n'drop thing needs more code clean up yet).

**Comment by pfalcon** [comment]
> When 'alt' will make it into PageView data model then there will be time to display it :)

Are you sure it's not there? https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/4b48fede2ae0f69c1c19802bb3a774c9751a5b2c/zim/formats/wiki.py#L577

> I also doubt about usefulness of it as it's much faster to just drop image in place than edit description (in each single page that links to this image!)

Consider that you sync you notebook to a phone, but don't sync images (because you have gigabytes of them). Then it's helpful to see *descriptions* of images in a viewer, rather than "broken image" icon with a path (depends on a viewer of course). All in all, there're uses for "alt", even though many people will never use them.

**Comment by introt** [comment]
Re: alt: #963
