### ISSUE TITLE
Editor with preview for edit single note

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1320]
Are there any editor with preview for edit single note (from inside Zim - as external editor) ?

I try ReText, Ghost editor, Notepad++ - but I cannot see good preview...

**Comment by jaap-karssenberg** [comment]
You can edit a page in a separate windows with the dev branch. Is that what
you are looking for?

Op vr 13 nov. 2020 00:48 schreef Nick222 <notifications@github.com>:

**Comment by Nick222** [comment]
Sometimes you need to edit a large note for a long time and carefully, focusing only on it.
In this case, not only the content of this note is important, but also its design.
For this I use text editors, but I did not find one among them who allows you to view the note as it will look in Zim after editing.

At the same time, it is undesirable to use Zim entirely, so as not to load into memory and accidentally damage other notes.

Is it clear enough that I wrote (using Google translate)?

**Comment by pfalcon** [comment]
> For this I use text editors, but I did not find one among them who allows you to view the note as it will look in Zim after editing.

That's why everyone (*) uses Markdown format for Zim notebooks (https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/26#issuecomment-688178350) - you can choose any of the dozens available Markdown editors. I have Zettlr and QOwnNotes installed here for example (can't find time to install and review a dozen other I have in the queue).

> At the same time, it is undesirable to use Zim entirely, so as not to load into memory and accidentally damage other notes.

Sorry, this is nonsense, you can't "damage other notes" if you use version control for notebooks, that's why everyone (*) uses git integration.


(*) irony
