### ISSUE TITLE
Editor slow if working on slow SMB mounts

### ISSUE THREAD

**Issue by mfriese** [zim-desktop-wiki/zim-desktop-wiki#1362]
It seems zim is slow, if working on slow smb mounts. Which is fine, if navigating. On the other hand once a file is opened I think editing should be fast. But still, it feels pretty slow, still.

**Comment by jaap-karssenberg** [comment]
Can you add detail on what exactly is slow or makes it slow? Maybe running
with debug switch can help setting what goes on?

Op wo 13 jan. 2021 10:13 schreef mfriese <notifications@github.com>:

**Comment by mfriese** [comment]
Thank you for the answer!

So I have mounted an SMB Volume through VPN.

When editing text it seems delayed. I would say it feels like 1/4 of a second between pressing a keyboard button until I see the resulting symbol/letter on screen. Somehow I fell like this might be directly related to the network speed cause in the evening when there are not that many people on our server it feels faster. I just tried it again and right now it feels pretty fast. Big difference to this morning.

It's strange cause I wouldn't think there is traffic when I just edit text.

Then, when navigating around files, it's also quite slow. Same with the server speed in the morning and evening. Which is not that big of a problem, as long as editing text is fast. I know our server was really slow today. Obviously a lot of IO is going on, when opening files and moving/renaming files. No problem. Just the slow text editing seems strange.

If that doesn't help you I can also have a look at the debug switch. I'm waiting for your answer first.

Thank you,
the app is outstanding!

**Comment by jaap-karssenberg** [comment]
I think the editing itself should be independent of the storage. However if
there is file access in the background that could cause she stutter in the
interface. Probably what you experience happens when Zim is busy checking
and updating the index, which requires scanning the folders. In the debug
output you will see start and stop events. Once index update is done it
should feel faster.

Op wo 13 jan. 2021 18:45 schreef mfriese <notifications@github.com>:
