### ISSUE TITLE
Multiple editable windows

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#153]
Currently when a page is opened in a new window the new window is read-only. Make these writable as well. 

Depends on #111 

Requires "navigation model" object that knows in which window to open a link

**Comment by sojusnik** [comment]
This would be for me a killer feature! Can't wait to test this out.

**Comment by Osndok** [comment]
I was thinking about this just the other day when using "gtg"... the real problem is concurrency... so perhaps it would be easier, an alternative, or "stepping stone" would be an option to open every page in it's own window (rather than having a one-page, central navigation, browser-theory). I kinda like the current model better, but I think one-page-per-window would one possible option to consider.
