### ISSUE TITLE
zim ignores preferred app (pdf viewer)

### ISSUE THREAD

**Issue by p-m-brown** [zim-desktop-wiki/zim-desktop-wiki#1531]
With ubuntu 18.04: okular is my default for pdf, but Zim launches evince

**Comment by jaap-karssenberg** [comment]
Try right click "open with" to change the application.

Development branch has fixed to follow the latest standards.

Op di 27 jul. 2021 13:53 schreef p m brown ***@***.***>:

**Comment by p-m-brown** [comment]
excellent, that fixed it, thank you. Of course, you mean 'right click-open with' inside zim, i had done it outside zim when i initially set the default

**Comment by roland-ruedenauer** [comment]
Working on Manjaro KDE I find Zim is not able to determine the default application for mimetype 'text/plain".

The reason here is the desktop environment determined from environment variable XDG_SESSION_DESKTOP is returning 'KDE' in capital letters, while the configuration file uses lowercase 'kde-' prefix.

```
[xxxxxx@xxxxxx]$ ll /etc/xdg/*.list
-rwxr-xr-x 1 root root 598 13. Aug 22:42 /etc/xdg/kde-mimeapps.list
```

The [specification](https://specifications.freedesktop.org/mime-apps-spec/latest/ar01s02.html) on freedesktop.org states:
> This is determined from taking the ascii-lowercase form of a component the environment variable $XDG_CURRENT_DESKTOP, which is a colon-separated list of names that the current desktop is known as.

Zim should take this into account when searching for mimeapps configuration and use a lowercase desktop name at
https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/gui/applications.py#L308

**Comment by jaap-karssenberg** [comment]
@Roland could you file a pull request for this ?  Thanks!

**Comment by jaap-karssenberg** [comment]
Merged fix specific for KDE
