### ISSUE TITLE
Search function raises blocking errors

### ISSUE THREAD

**Issue by alesarrett** [zim-desktop-wiki/zim-desktop-wiki#1602]
Hi, after the last update to Zim 0.74 on Ubuntu 20.04, I'm not able to use the Search function (Shift+Ctrl+F).
At first it showed a never-before-appeared error on various notebook pages, saying that the page existed but it was not a wiki page, asking to import it. After the successful import, a second page error, and a third, ... now I have a different error related to invalid characters (see image), but I cannot try to solve it, because the error text in the window is cut off.
![image](https://user-images.githubusercontent.com/1692316/134027670-9597b398-cf96-4b87-a2f2-a6cfc07ddb09.png)
Currently I'm no more able to search on the notebook because of this error blocking the search.
Is there something I can do to solve it, or to provide you more detailed feedback?
Thanks

**Comment by ZtzEAcRsND** [comment]
On your ubuntu system, if your zim is logging errors to ``/tmp/zim<random>`` you might try in a terminal window:

$ ``find /tmp/zim* -iname zim.log -exec grep -iH "Could not read.*home.ale.Notebooks.ZimWiki" {} \;``

Which should print the full line of text that is cut off (hopefully the errant file name). The find command result should also give you the path to the zim.log file so you can look further.

I used the following to get the complete line and file name when dealing with the 0.73.5 to 0.74.0 text file as (not) attachments which gave me the same errors as you.

$ ``find /tmp/zim* -iname zim.log -exec grep -H  "ERROR.*Page not available" {} \;``

**Comment by fdt-dev** [comment]
It's probably some Zim files wich are missing the standard header that Zim usually writes. That was the issue for me anyway.

**Comment by jaap-karssenberg** [comment]
The import question is indeed related to pages without headers - but these
should not show up during search.

The error shows is due to unicode / locale encoding and relates to a
specific page containing characters that are not unicode encoded. Again
should not block the search.

Debug log can help identifying the offending file to fix the issue. Will
look into why search blocks on this issue and why search triggers import.

**Comment by alesarrett** [comment]
Thanks all, the suggestion bt @ZtzEAcRsND  has helped me in finding the broken file and I managed to fix it. Now I can search through Shift+Ctrl+F

**Comment by ZtzEAcRsND** [comment]
@jaap-karssenberg (just guessing) that a source of errors come from a zim (<074.0, e.g., 0.73.5) index.db that included text file(s) w/o the zim headers as zim pages, even if the text file name or content is basic ASCII. When the zim notebook is newly opened in zim 0.74.0 the index.db from the 0.73.5 version file is reused.

I tested by: 
1. Creating a new 0.73.5 notebook (name: zim-test), adding page1 and page2. then opening/creating a page1 attachment folder, and creating a text file w/o zim header (name: not-attached-text-file.txt into the attachment folder. The non-zim text file became an indexed zim page. Close zim.

2. ``$ strings  ./zim-test/.zim/index.db | grep not-attached`` shows (only part is pasted)
    ``Home/page1/not-attached-text-file.txt
not-attached-text-filenot-attached-text-file1fe20d2681612682681611791ba18e18226818e2962681a51c51e018e011d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d0102020202020202020202020202020202020202010163740163af0164de013d6701609d0164de0164de01609d01611d01622e01618a01614f013d670164de01618a0165b00164de013d670161d80162630162f501618aA``

3. Opened the zim-test notebook and 0.74.0 and did search (<ctrl><shift>f) "find text". Got ``page not available error``. zim.log shows:
``/tmp/zim-to5gw75n/zim.log:zim.notebook.notebook.PageNotAvailableError: Page not available: Home:page1:not-attached-text-file
/tmp/zim-to5gw75n/zim.log:ERROR: Page not available: Home:page1:not-attached-text-file``

4. clicked on the attached non-zim file, answered 'yes' to the import. Then repeated the search without an error. 
5. closed the notebook. strings on index.db w/grep for 'not-attached' file name is similar to above. 
6. deleted the zim-test index.db and removed the zim wiki header in the 'not-attached-text-file.txt'
7. opened the zim-test notebook in zim 0.74.0. 'not-attached' file is not attached and search works without error. No prompt to import the attachment unless I click on the file via attachment view.
8. closed zim and zim-test notebook
9. strings on the zim-test index.db is different now:
``$ strings  ./zim-test/.zim/index.db | grep not-attached 
Home/page1/not-attached-text-file.txt
Home/page1/not-attached-text-file.txt``

Notes
1. the notebook.zim 'sharable' option is set to 'false' in both 0.73.5 and 0.74.0 so I'm using the same index.db file. 
2. sometimes reopening the zim-test notebook after deleting the index.db gives a nasty error: ``OperationalError: attempt to write a readonly database `` which may be caused by a file lock or something else I did....
3. deleting index.db seems drastic, but works sometimes for me.
4. thanks for all you're doing. and the team.

**Comment by PierreRust** [comment]
Sorry to post on a closed issue, I can create a new one if needed, or move my question to discussions.

I add the issue with the blocking search (see the duplicate #1656 ) and I've tried the fix from 605b06c ; with that the search does not block any more. However, any page without header does not show up during search, even though there are definitely many  zim-created pages (admittedly relatively old) among these files. Is that an expected behavior ? is there any way to add headers to these pages to have them searched ? It seems I can import them, but that would require trying all the files using the index to find the files without header, which is tedious on a rather large notebook (> 1000 pages).

Thanks !

**Comment by jaap-karssenberg** [comment]
Yes please capture this as a new issue as it is no longer about search but
about batch import.

Op wo 6 okt. 2021 09:25 schreef Pierre Rust ***@***.***>:
