### ISSUE TITLE
New Zeitgeist plugin`s bug ?

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1640]
Open Zim - edit opened note without switching to another note - save and close Zim - cannot see any entry in Zeitgeist journal.

Open Zim - switch to another note without editing - close Zim - see new entry in Zeitgeist journal.

Is it right?

Xubuntu 21.04
Zim 0.74.1

**Comment by mstimberg** [comment]
You are quite right, this is broken, see #1643 for a fix.

In your test, the saving should send a "modify event" due to the save, but this wasn't working at all. In addition, any opened page should also appear in the Zeitgeist journal just for getting accessed, but this did not work because the page was already open when zim started (the plugin gets loaded *after* the page-opened signal).
