### ISSUE TITLE
inserting link to header in other notebook (interwiki link) broken

### ISSUE THREAD

**Issue by mtill** [zim-desktop-wiki/zim-desktop-wiki#1938]
Hi!
when trying to insert an interwiki link to a header from another zim notebook, the link cannot be opened correctly. Instead, a new subpage is created.
BR
mtill

**Comment by mtill** [comment]
steps to reproduce:
in notebook A, right-click on some header and choose "Copy link to this location".
Paste the link to some page in notebook B. Click the link - it will not open the right page in notebook A (but some non-existing new subpage).
BR
mtill

**Comment by introt** [comment]
Hi @mtill, thanks for filing the issue, but please use & fill out the appropriate template next time.

For clarification: the new subpage is opened in the target notebook `iw` at the path `:Page:SubpageHeading` for the link `iw?Page:Subpage#Heading`; the `#` seems to get removed by `makeValidPageName` here

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/458688c2042602ba4a0c94dab8b1e11f9008911d/zim/notebook/page.py#L150

because it's included in the regex:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/458688c2042602ba4a0c94dab8b1e11f9008911d/zim/notebook/page.py#L26-L33

**Comment by mtill** [comment]
thank you for the hint - will use the bug template next time!

**Comment by introt** [comment]
Related: PR #1626's commit 3a1302df6a9374a3e944748d5333594ac6fbfae5, "fix open link with anchor in other notebook"
