### ISSUE TITLE
Corruption of text buffer after ctrl-up and undo buffer after ctrl-z

### ISSUE THREAD

**Issue by destenson** [zim-desktop-wiki/zim-desktop-wiki#1992]
I was editing a long document mostly filled with bulleted list items. Then I used the ctrl-up command to move some items higher in the list. After doing this a few times, the text became corrupted, inserting the lines in the middle of the lines above. So I pushed ctrl-z to undo & it undid in a corrupted way... something got totally messed up. In the past I noticed there's a .git directory in the notebook folder, so maybe it saved some history. No. It staged all the corrupted changes & hasn't been committed in 4 months. WTH.

**Environment (please complete the following information):**
 - 0.73.5
 - windows
 - English

I used to love Zim. I've used it for several months without major concern. Now it's burnt me bad. I can't trust it any more. I can't use a tool I can't trust.

**Comment by ofossum** [comment]
> Then I used the ctrl-up command to move some items higher in the list.

Where is this command enabled?
I couldn't find it via the settings nor was i able to do such a thing.
Could not reproduce this behaviour.

 **Environment (please complete the following information):**

* 0.74.3
* Linux (Arch)
* German

**Comment by introt** [comment]
Hi Dennis,

Sorry to hear you've got got by the line sorter plugin bugging out (@ofossum, you can find it in the plugins - the description will mention these additional features in the next version).

While your description leaves much room for interpretation, what I can say is that it's been changed around a bunch since 0.73.5 (some of which regressed to producing behavior similar to what you've described, but which has since been fixed, see #1960), and 0.75 should bring about more robust undo/redo functionality ([fb24575](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/fb2457538b93ad68b8985fb8fd9d2c8e34e627be)).

Feel free to test out the upcoming (in this case more stable) unstable version by cloning the `develop` branch!

> In the past I noticed there's a .git directory in the notebook folder, so maybe it saved some history. No. It staged all the corrupted changes & hasn't been committed in 4 months. WTH.

As much as it pains me to say this, what you're describing here is the intended behavior, not a bug. Enabling the version control plugin doesn't enable automatic commits by default, as can be seen after clicking the Configure button:

![image](https://user-images.githubusercontent.com/26069787/161382321-688e26f4-ac77-48c4-9b74-694ed2f499d7.png)

While [version control](https://en.wikipedia.org/wiki/Version_control) software can be used for backing up, it doesn't create backups by default; this is true outside of Zim as well.

Even while regularly committing changes, you only have one copy of the data and the incremental changes stored in one place; a [backup](https://en.wikipedia.org/wiki/Backup) by definition requires at least two copies stored separately - at the very least in different directories on the same disk. Some opinionated definitions also require verifying that the backup is restorable for it to count as a "true" backup.

If it's any consolation, you can take solace in knowing that [it could've been much worse](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1615).

**Comment by introt** [comment]
We're going to need (reproducible) examples of text corruption on 0.74.3 to work a fix. If the bug is no longer present on `develop`, it is worth considering whether efforts should be focused on releasing 0.75 instead of hotfixing the "old" parse tree.
