### ISSUE TITLE
Pasting anchor link across pages sometimes adds anchor to pasted link's displayed text

### ISSUE THREAD

**Issue by tlayton90** [zim-desktop-wiki/zim-desktop-wiki#1993]
**Describe the bug**
When a link to an anchor (e.g. 'some-anchor') is copied or cut from one page and pasted into another page, if the displayed text of the original link matches the name of the page (e.g. 'Foo') containing the anchor, the pasted link's displayed text will include the anchor as well the page name (e.g. "Foo#some-anchor").

**To Reproduce**
1. Create a new notebook.
2. In the created notebook, create three sister pages: 'Foo', 'Bar', and 'Baz'.
3. In Foo, create an anchor (e.g. via a header) called 'some-anchor'.
4. In Bar, create a link to some-anchor in Foo, with the displayed text "Foo". 
5. Copy or cut the link in Foo.
6. Paste the link in Baz.

**Expected behavior**
The pasted link should still have the displayed text "Foo" rather than "Foo#some-anchor".

**Environment (please complete the following information):**
 - Version: 0.74.3
 - OS: Windows 10
 - Language: English

**Additional context**
When a link is pasted across pages, Zim automatically updates the link to ensure that it remains valid with its change of position in the page hierarchy. If the link's displayed text matches the original link itself (for some definition of 'matches'), Zim also updates the displayed text to maintain that match in the updated link. I would guess that this bug stems from a flaw in the 'matching' logic, resulting from its failure to fully account for the recently-added anchor feature.

**Comment by introt** [comment]
Hi @tlayton90 and thanks for the detailed bug report!

I can reproduce this on 0.74.3 but not on the latest `develop` which contains Roland's anchor logic fixes.

It should be noted that copying via selecting the text behaves differently than copying via the right-click menu; in the latter case, the expected behavior is not for the displayed text to be copied.

I'll leave this ticket open till the release of 0.75. In the meantime, feel free to try out the `develop` branch and open a new issue for any (un)related issue you may encounter.
