### ISSUE TITLE
Window state with multiple notebooks

### ISSUE THREAD

**Issue by plodalong** [zim-desktop-wiki/zim-desktop-wiki#2019]
**Describe the bug**
the .zim file in the root folder (below which reside the actual notebook page files) has a state.conf file remembering the last used window state including side panes etc. When using multiple notebooks, say A,  B, closing B while A is still open results in notebook B's window state not being remembered.

**To Reproduce**
1. open two notebooks
2. activate and change the widths of the side-panes in the second notebook so it's different to the first
3. close the second notebook
4. close the first
5. open the second

**Expected behavior**
I'd expect both books to retain independent window states.

**Environment (please complete the following information):**
 - Version 0.73.5 as supplied by debian stable repos
 - Linux Debian 11 Bullseye

**Additional context**
I'm not a programmer, but do appreciate zim very much and have used it for years. Sorry if this isn't a bug and the program behaves as you intended. I just think most users will expect window state to be preserved. Since the help files suggest using multiple notebooks I have assumed window state will be preserved. I used to use only one huge notebook, so this wasn't an issue, but I've recently split the content out into three. It would even be OK if the last used state was applied to the next notebook to open, but I find unless you open the last closed notebook first, they default (presumably because the config file doesn't match the notebook being opened) to a state without panes at all.

Thanks!

**Comment by introt** [comment]
Hi! Thanks for the thorough report, that is indeed a bug and not expected behavior.

Version 0.74 should have way more robust state saving - in addition to multiple notebooks, it saves the state on multiple windows (pages can be opened in new editable windows, it's great!) - and I can not reproduce the bug there. I tried with both or only one of them having `shared=False` in the notebook.zim config file, and both saved window size and sidepane state independently on both accounts.

If you'd like to give 0.74.3 a shot, you can either use the Flatpak package from Flathub or `git clone` the repo and point your launcher (`.desktop` file) to the `zim.py` script within - no compilation or additional dependencies needed (the 0.73.5 package pulled those in)!

We don't (and can't, as we're not the package maintainer) support older releases, so I'm going to close this ticket as fixed . If you encounter this issue again on 0.74.3, feel free to reopen it, and we'll take another look. Thanks!
