### ISSUE TITLE
Navigation not working in new windows

### ISSUE THREAD

**Issue by Pseudavid** [zim-desktop-wiki/zim-desktop-wiki#2157]
**Describe the bug**
In Zim, I can right-click any link and choose "Open in new window". A second Zim window will open with the intended page. This window allows editing. 
However, clicking links in the second window will open that link in the first window. Also, the second window lacks a page index sidebar, as well as back and forward buttons.

**Expected behavior**
The second window should allow navigation the same as the main window: clicking links and, optimally, having a page index sidebar.

**Environment (please complete the following information):**
 - Version 0.74.3]
 - Linux (Ubuntu 22.04)

**Additional context**
Sometimes I'd like to integrate ideas from other notes in a note. Browsing older notes can be useful to find connections among ideas, which is one of the strengths of a wiki (it doesn't impose an structure, it lets you build your own). However, currently Zim doesn't let you browse older notes while keeping your current note open and editable.
There are fancier approaches to this, like tabs and split screen. However, I think that a simple new window would be more than enough, if that new window was actually navigable.
Thanks!

**Comment by introt** [comment]
The _New Windows_ are currently not navigable by design (thus the lack of a page index), but as a workaround you can browse your notebook using your web browser by using Tools > Start Web Server and pointing your browser at http://localhost:8080

Edit:

>  However, currently Zim doesn't let you browse older notes while keeping your current note open and editable

Actually, the current way to do that would be to open your current note in a New Window (which are now editable) and browsing your older notes in the Main Window.
