### ISSUE TITLE
Zim version 0.75.0 for Windows crashes after making the first update in a notebook

### ISSUE THREAD

**Issue by YuryDudorov** [zim-desktop-wiki/zim-desktop-wiki#2164]
**Describe the bug**
Zim version 0.75.0 for Windows has been just installed over the previous version 0.74.3. The application has crashed after an attempt to insert a new line into notebook page. The output produced by the '-D' option is attached (Zim-debug-output.log).

**To Reproduce**
I have opened four notebooks one after another and tried to insert an empty line into the last notebook. Zim crashed without any error diagnostics.

**Environment (please complete the following information):**
Version 0.75.0
OS: Windows 10 Version 20H2

[Zim-debug-output.log](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/9690738/Zim-debug-output.log)

**Comment by mtill** [comment]
Hi!
having the same stability issues with the 0.75 release, I updated the build environment and recompiled ZIM from scratch. This new binary seems to be stable so far....
BR
mtill

**Comment by jaap-karssenberg** [comment]
Afraid the debug log doesn't give information that is useful in this case.
Can't reproduce on my side.

Did use a fully up to date build environment for the installer, so not sure
what delta could help to improve.

Let's monitor if more instability is seen.

--- Jaap

**Comment by jaap-karssenberg** [comment]
Interestingly, I accidently stumbled on a similar copy-paste to segfault
issue. I have not seen those before and might indeed be related to the
update of my msys environment I did last week. Even more interestingly,
updating msys once more, the issue seems gone. I did notice, there was a
gtk3 package in the list of updated packages.

So @mtill is probably right that updating the build environment could get
rid of the issue. Will re-build the installer after number of bug fixes and
this one probably gone then.

--- Jaap

**Comment by menthalo37** [comment]
Hello
on Zim 0.75
I have (regularly) such crash without log nor error I could report here, following this precise action : 
paste from (any) another software (for instance : url coming from browser like firefox, link from outlook, etc.)

I still manage to paste such content through pasting first in notepad (++) 
and then : select_all-copy-paste again into Zim
E.

**Comment by jaap-karssenberg** [comment]
Expect this issue is solved in 0.75.1 - please comment if it appears again
