### ISSUE TITLE
Multiple nodes can be removed as a group when created in a specific manner

### ISSUE THREAD

**Issue by zogommog** [zim-desktop-wiki/zim-desktop-wiki#2199]
**Describe the bug**
I discovered that when creating pages, you could enter values such as "node:subnode:value1", and so forth. This creates a hierarchy of nodes as one might expect like node-->subnode-->value1. I don't know if this is an intended feature or just something I stumbled upon, but it has turned out to be rather convenient in some circumstances in order to speed the creation of nodes to take one command rather than multiple commands.

When this method is used to create nodes, I've noticed that if you delete one of the subnodes, then all of the nodes associated with the command used to create them can get deleted.

I am not entirely sure if this is a bug or a deliberate feature or unexpected behavior to unusual input. 

**To Reproduce**
1. Create a new sub page (node), named "test:subnode:value1" with any template.
2. Delete the node for "value1" (it could also be one in the middle such as subnode).
3. Note that all the newly created nodes are deleted, including the parents "test", and "subnode".

**Expected behavior**
I expect that when sub-nodes are deleted (however they were created), that there is no automatic response that also deletes the parent nodes. If this method of creating nodes is not deliberate, it could be validated as incorrect syntax though it is handy. If the feature is deliberate, then once the initial creation of multiple nodes completes from a single create sub-page command, the created nodes should ideally not behave any differently than if they were each created individually.

**Environment (please complete the following information):**
Version: 0.73.5 (latest version in the distribution)
OS: Debian GNU/Linux 11 (bullseye)

**Additional context**
If two or more nodes using the same path are created, they seem to prevent the parent nodes being automatically deleted. For instance if you create:

"test:subnode:value1"
"test:subnode:value2"

...and then you delete the value2 node, "test" and "subnode" will not be removed. I only tested this by creating sub pages, so I'm not sure what would happen if these were the first pages created at the root level. There ther considerations I haven't tested,

**Comment by introt** [comment]
This is intended behavior; your mental model of how Zim works is just a bit off. Let's try to fix that!

Zim's pages in the index are simply text files on the filesystem. When you create the page `test:subnode:value1`, Zim creates the following hierarchy to represent the parent and sub pages (directories emphasized with brackets):

```
[test]
└── [subnode]
    └── value1.txt
```

As can be seen here, the pages `test` and `subnode` do not have a corresponding text file. Thus if you delete `value1.txt`, the only "real" page in the hierarchy, either directly or by deleting one of its parents, Zim will happily clean up the empty directories for you.

Compare this to navigating to `test:subnode:value1` using Jump To, and then navigating to another page without modifying `value1` - the whole hierarchy disappears, because it is not backed by any existing pages.

In your other example, the hierarchy isn't empty (`test/subnode/value1.txt` exists) so it isn't deleted.

In neither case does Zim delete existing pages. If you want to keep the hierarchy, you can eg. open and modify `subnode` to prompt the creation of `test/subnode.txt`. I do agree that these virtual pages should show up differently in the index, but that's a feature request and belongs in Discussions.

I hope this helps, have fun exploring Zim!

**Comment by zogommog** [comment]
introt,

Thank you for taking the time to respond. I can see two points of view for how it might behave. On the one hand, it could be inconvenient for people to have to clean up empty hierarchies, or the other way around if you want them to persist (because you plan to replace the last page with something else).

> I do agree that these virtual pages should show up differently in the index, but that's a feature request and belongs in Discussions.

Knowing that the virtual pages are virtual pages (versus not) could help some with confusion for cases where you do not recall which method you originally used to create pages. I wonder though if people tend to want the behavior usually one way or the other (consistently) if it could instead be a candidate for a feature request for the behavior itself. For instance, perhaps there could be an option that defines that pages are never created "virtually", and will always persist until manually deleted even if the associated hierarchy is empty.

I'll consider it some more and perhaps move this topic over to the Discussions area. Mainly, I just wanted to say thanks for the detailed response!

**Comment by jaap-karssenberg** [comment]
As soon as you type some content, the bide is no longer virtual. So the
mechanism to choose is really straight forward.

Jaap

Op do 20 okt. 2022 19:15 schreef zogommog ***@***.***>:

**Comment by jaap-karssenberg** [comment]
Also nodes that are linked from other nodes are persistent. So if your goal
is to quickly populate an hierarchy. Just type it the table of contents as
links.

Jaap

Op vr 21 okt. 2022 13:29 schreef Jaap Karssenberg <
***@***.***>:

**Comment by zogommog** [comment]
> As soon as you type some content, the bide is no longer virtual.
> Just type it the table of contents as
> links.

Thanks, these are helpful tips. I confess I feel a bit embarrassed, I read the manual at some point but it seems I need to refresh my memory because I see a lot of this is covered there. Maybe some things changed. So far, I do have some interesting things to point out at least (that maybe I haven't figured out from the manual yet):

1) If I copy paste a bunch of lines (in a valid syntax) they don't automatically turn into links. They turn into links if I put the cursor at the end of them and press enter. This doesn't really help to create several pages at once as much as it seems like it could if it converted them all at once. 
2) Some combinations of them do not seem to be working to be turned into links no matter what I do. Examples:
+xyz:aabc:123  <-- works when enter is pressed at the end
+123:xyz:abc <-- does not seem to turn into a link pressing enter at the end. It can be created with the insert link command from the menu though. Seems to be related that it starts out with numbers, but I can't confirm that is the only condition.
3) These virtual pages (before you type anything to make them permanent) are distinguished by being "greyed out/italic", so that's good. I guess, that is probably what the other version of them needs as well, if you say create a new subpage like "xx:yy:zz" from the context menu in the index. It would be consistent.

Perhaps I can edit the page directly at the file level instead of within the wiki to create a block of links at once if I want to create a hierarchy quickly, but it does seem like it would be nice if the handling of turning text into links could work on a larger block of text copy/pasted in directly from within the program.

Disclaimer: Clearly I need to keep reading the manual some more, so these are only preliminary observations tied to the suggestions above.

Thanks for the tips Jaap! Maybe I'll circle the wagons again another time after I'm finished becoming reacquainted with the docs and have exhausted my testing further.

Fun thing, trying to write out
`+xyz:abc:123`
 turns abc into a graphic in this editor.
+xyz:abc:123

**Comment by introt** [comment]
1. Other word breaks like a space also work; you can also write links `[[like this]]` inside Zim (ie. using full wiki syntax instead of the auto-formatted "shorthand") and use copy & paste with them as they'll show up as links only after a page reload (ctrl+r).
2. I can't reproduce that on 0.75, both examples behave identically. Writing `[[raw wikitext]]` should solve these kinds of issues here, too.
3. Agreed. Though since the "other version" has real subpages & some resemblance in the file system it should probs look distinct from the "100% virtual" pages.

**Comment by introt** [comment]
Re #3, I was wrong - those linked-to nonexistent shown-in-gray-italics pages can have attachments, so they do have "some resemblance in the file system"

**Comment by introt** [comment]
If you want to open a ticket for the visual indicator, the term used in the codebase seems to be "vivification"

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/82b7fb978891302e5eeb95ce95bde8d7e857f191/zim/plugins/pageindex/__init__.py#L618-L623
