### ISSUE TITLE
Unify automatic unfold/fold behaviour

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#2205]
**Describe the bug**
After [this](https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/2113) merge the unfold/fold issue is fixed, but I also observe that when jumping to another page through the history bar or bookmarks bar or the "jump to" window etc., meaning NOT using the index/tag side pane to jump to another page, then the current page with its subpages isn't automatically folded, when switching to another page with subpages. So Autofolding/-unfolding works reliably only when using the index/tag side pane. Of course, `Automatically expand sections on open page` and `Automatically collapse sections on close page` have to be enabled in the options of the index/tag side pane.

Is this by design?

I would prefer if the folding/unfolding mechanism would work consistently, regardless of whether the side pane or other methods are used to jump to pages.

BTW, manually folded/unfolded pages shouldn't be affected by the automatic folding/unfolding mechanism switchable in the settings (as mentioned above), as it is already done now.

**Environment (please complete the following information):**
 - Version: 0.75.0
 - OS: Ubuntu 22.04

**Comment by introt** [comment]
Doesn't seem to be by design; the page changes should emit the `page-changed` signal, triggering `on_page_changed`

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/82b7fb978891302e5eeb95ce95bde8d7e857f191/zim/plugins/pageindex/__init__.py#L90-L91

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/82b7fb978891302e5eeb95ce95bde8d7e857f191/zim/plugins/pageindex/__init__.py#L108-L109

And further `set_current_page`, which seems to be responsible of auto-expanding and auto-collapsing

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/82b7fb978891302e5eeb95ce95bde8d7e857f191/zim/plugins/pageindex/__init__.py#L618-L643

> BTW, manually folded/unfolded pages shouldn't be affected by the automatic folding/unfolding mechanism switchable in the settings (as mentioned above), as it is already done now.

True as per the manual. This is tracked by #2119

**Comment by introt** [comment]
> when jumping to another page through the history bar or bookmarks bar or the "jump to" window etc., meaning NOT using the index/tag side pane to jump to another page, then the current page with its subpages isn't automatically folded, when switching to another page with subpages

I can't reproduce this on 82b7fb978891302e5eeb95ce95bde8d7e857f191 using the "jump to" dialog nor the bookmarks bar, unless I have manually expanded the page before. Given the log below, I think we're going to need some more logging to get to the bottom of this (ie. `DEBUG: (Auto)collapse page: Foo:Bar (Foo:Bar)` etc)

```
INFO: Open page: Foo:Bar (Foo:Bar)
DEBUG: Closed dialog "Jump to"
DEBUG: Action: show_jump_to
DEBUG: Opening dialog "Jump to"
DEBUG: Dialog response OK
INFO: Open page: Foo2:Bar2 (Foo2:Bar2)
DEBUG: Closed dialog "Jump to"
DEBUG: Action: show_jump_to
DEBUG: Opening dialog "Jump to"
DEBUG: Dialog response OK
INFO: Open page: Foo (Foo)
DEBUG: Closed dialog "Jump to"
DEBUG: Action: show_jump_to
DEBUG: Opening dialog "Jump to"
DEBUG: Dialog response OK
INFO: Open page: Foo2 (Foo2)
DEBUG: Closed dialog "Jump to"
```

**Comment by jaap-karssenberg** [comment]
Assume double of other issues on this behavior
