### ISSUE TITLE
Ignoring Image Exif rotation metadata

### ISSUE THREAD

**Issue by MurrayVK3** [zim-desktop-wiki/zim-desktop-wiki#2228]
**Describe the bug**
Exif rotation metadata in images is ignored.

**To Reproduce**
Insert a jpg with rotation metadata

**Expected behavior**
Image should be displayed orientated per the metadata

**Screenshots**
![image](https://user-images.githubusercontent.com/28350144/202887547-1eebd1c8-43a7-420c-87a6-13dda074ee13.png)
this image displays upright in other image viewers

**Environment (please complete the following information):**
 - Version 0.75.1
 - OS:Linux

I believe this regression started with version 0.75

**Comment by introt** [comment]
Thanks for the report!

The gtkD docs feature a function called "[applyEmbeddedOrientation](https://api.gtkd.org/gdkpixbuf.Pixbuf.Pixbuf.applyEmbeddedOrientation.html)" , but we seem to lack that - however, we can implement our own using a combination of [`Pixbuf.rotate_simple`](https://lazka.github.io/pgi-docs/GdkPixbuf-2.0/classes/Pixbuf.html#GdkPixbuf.Pixbuf.rotate_simple) (which rotates an image by a multiple of 90 degrees) and [`Pixbuf.get_option("orientation")`](https://lazka.github.io/pgi-docs/GdkPixbuf-2.0/classes/Pixbuf.html#GdkPixbuf.Pixbuf.get_option):

> Since 2.12, the TIFF and JPEG loaders return an “orientation” option string that corresponds to the embedded TIFF/Exif orientation tag (if present).

Just need to wrap that in a try-catch block et voilà!

**Comment by MurrayVK3** [comment]
I've just realized it only happens when the image view is resized via the context menu 'Edit Properties'.  Clicking reset in that dialog to display the image at its full size results in the correct orientation.

**Comment by introt** [comment]
Thanks for sharing your finding @MurrayVK3! Presumably the resizing is done using the raw, non-rotated buffer. Will need to be addressed.

Edit: could you share logs from Tools > View debug log? I'll need logs from two separate runs, one with resizing and one without (or two image files). I'm interested in whether this has to do with falling back to Pillow for image loading, as that loses the metadata. I'm guessing it's falling back due to failing to scale, since displaying at full size works (and our fallback lacks any orientation related functionality).

**Comment by kareliot** [comment]
This is marked as completed, but in Version 0.75.2 this issues still persists.
When I import an image, the rotation is correct but when I resize the image as described by MurrayVK3 then the image rotation is not correct.
