### ISSUE TITLE
shortcut <ctrl><T> changed behavior

### ISSUE THREAD

**Issue by Dibal** [zim-desktop-wiki/zim-desktop-wiki#2232]
**Describe the bug**
In the past <ctrl><T> formated text as code block. Internal format: three quotes like ''' code...'''.
Now this shortcut formats all marked lines in double qoutes: ''line1'' /n ''line2'' 

**To Reproduce**
1. Mark text
2. <ctrl><T>

**Expected behavior**
formated codeblock with intent

but get single line format only.

**Environment (please complete the following information):**
- Linux, Zim 75.1

**Additional context**

Problem may be solved by new shortcut for "codeblock".

Interim solution:
Write:
'''
code
'''

and press <ctrl><R> (reload page)

**Comment by introt** [comment]
Likely related to internal parsetree changes. To format multiple lines as a code block, you now need to start the selection from the beginning of the next line, eg.

```
to format this line as verbatim, place the cursor
| <- here & select the line above
```

This results in the expected verbatim "block":

![image](https://user-images.githubusercontent.com/26069787/204031503-f88386ae-0237-4ddf-8a93-51227f273f43.png)


@jaap-karssenberg is this intentional?

**Comment by Dibal** [comment]
Right!
It works from down to top, thanks for the hint.

(I usually mark text from top to bottom; in this case the format fails.)

**Comment by jaap-karssenberg** [comment]
Just tested on latest develop and works as intended. You get a block if you select multiple lines, and inline if selection is on a single line.

No need to select upwards, as long as your selection really includes the end of line, so start and end of the selection have different line numbers.
