### ISSUE TITLE
Changing line with ///

### ISSUE THREAD

**Issue by huseyinCkr** [zim-desktop-wiki/zim-desktop-wiki#2283]
This is zim 0.73.1
Platform: nt
Locale: tr_TR cp1254
FS encoding: utf-8
Python: (3, 8, 3, 'final', 0)
PyGObject: (3, 36, 1)

======= Traceback =======
  File "zim/gui/pageview.py", line 6003, in do_activate_link
  File "zim/gui/pageview.py", line 6017, in _do_activate_link
  File "zim/notebook/notebook.py", line 1008, in resolve_file
  File "zim/fs.py", line 1038, in __init__
  File "zim/fs.py", line 352, in __init__
  File "zim/fs.py", line 381, in _parse_uri
AssertionError: Can not handle non-local file uris

Error occur while editing:
while true;do am start -n  com.android.gallery3d/.app.MovieActivity -d file://sdcard//Download////[[ftp://195.214.150.238:2121/23.mp4|23.mp4]] ; sleep 60; done;

/// -> //

**Comment by introt** [comment]
It seems you're using Zim 0.73.1 - please update your version, as we don't support older releases.

On Zim 0.75.1 editing the string doesn't produce an error, but clicking on the link does. [This seems to be expected behavior](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/develop/zim/newfs/base.py#L389), but could pop up a nicer looking error as discussed at eg. #2256.

Furthermore, links inside links aren't and really can't be supported. If that's not what you were going for here, I suggest using the `verbatim` formatting (Format > Verbatim).
