### ISSUE TITLE
[question] ZimWiki window shadows and other special effects

### ISSUE THREAD

**Issue by dene14** [zim-desktop-wiki/zim-desktop-wiki#2355]
Hello!

Is it possible to disable ZimWiki window shadows and any other special effects (if any)? I prefer to have a DE w/o any animations, special effects and other prettiness. And ZimWiki looks like the only app that has this shadow around the window...

Also, window seems doesn't support Tiling or hot corners feature for cinnamon, which is quite strange and I don't know how to fix. Everything else is working just fine, e.g. slack, firefox, chrome

**Comment by introt** [comment]
Hi! Please see #2007 for more information. TL;DR: prior to Client Side Decorations, shadows were not drawn by apps themselves. You can disable CSD:s in Zim by disabling "Show controls in the window decoration". This may or may not also fix tiling - it may also not work due to the window requiring a certain minimum size, which can currently be worked around by closing the panels before tiling by pressing F9. Hope this helps!

**Comment by dene14** [comment]
Thank you very much @introt ! Everything works as expected now!
