### ISSUE TITLE
Trimming space in marked text

### ISSUE THREAD

**Issue by strepon** [zim-desktop-wiki/zim-desktop-wiki#2362]
**Describe the bug**
Space is trimmed when used at the end of marked text.

**To Reproduce**
1. Create a new page.
2. Type e.g. `**example: **` on it.
3. Save the file.
4. Open the file - the "example" text is formatted in  bold.
5. Add second line with `**example: **` again.
6. Save the file - the first line is changed to `**example:**`.

**Expected behavior**
The first line should remain unchanged.

This blocks using of a workaround for using italics mentioned in #1147.

**Environment (please complete the following information):**
Version 0.75.1, Ubuntu 23.04, cs locale. This did not happen in version 0.74.

**Comment by introt** [comment]
Thanks for the report, confirmed on 34b2d39a4aef83285e43840e12ffc47ec021e466

**Comment by myrdd** [comment]
It happens with any other formatting, e.g. monospace.
It also happens at the beginning of the formatting, so `'' example ''` gets `␣''example''␣`—with `␣` being a space char.

**Comment by jaap-karssenberg** [comment]
Yes, this is the expected behavior. Since the formatted whitespace is not visible in the editor, the editor tries to closely match the visible content when saving the wiki format.

**Comment by myrdd** [comment]
Sometimes I prefer single-line verbatim formatting (`''`) over the multi-line one (`'''`) in order to be able to use additional formatting like marking. See this example:

`''    indented text''` ← this is what I want
gets changed to  
`    ''indented text''` ← the indentation is no longer verbatim, so it's narrower

---

Now, when I use formatting like strong, mark or strike, this will happen:

`''foo␣''__''bar''__`  ← this is what I want
gets changed to  
`''foo''␣__''bar''__` ← the space character (`␣`) is no longer verbatim-formatted, so it's narrower

---

Similarly to the workaround in #1147, I used to use this workaround:

`''foo = 'bar'␣''` ← the space at the end is the workaround
..but now it gets changed to
`''foo = 'bar'''␣` ←here, the second apostrophe (`'`) isn't verbatim (which is the ”bug“)

---

To be fair, I have to say this is not a severe issue. Thanks for the really great application!
