### ISSUE TITLE
Wrong icon for highlight

### ISSUE THREAD

**Issue by ghost** [zim-desktop-wiki/zim-desktop-wiki#2522]
the icon underline U means underline, not hightlight. Highlight icon should be a marker pen. When I want to underline something important, I don't want to hightlight it. This happens on Ubuntu 22.04.3 LTS

**Comment by jaap-karssenberg** [comment]
This is a long standing "won't fix" mostly because there is no mark icon on
the default themes cross platform.

If it really bothers you, the easy fix it to modify the style config and
make marked text show underlined instead of highlighted :)

Regards,

Jaap

Op di 21 nov. 2023 11:23 schreef dave-iMac ***@***.***>:

**Comment by ghost** [comment]
Jaap,
Can you show me how to open he style config and make the change. Thank you.

**Comment by jaap-karssenberg** [comment]
There is a .ini config file which had a section per style tag.

Please see the information at
https://zim-wiki.org/manual/Help/Config_Files.html

Specific the section on GUI style config.

Regards,

Jaap


Op wo 22 nov. 2023 07:44 schreef dave-iMac ***@***.***>:
