### ISSUE TITLE
ppa packages not signed, cannot be installed

### ISSUE THREAD

**Issue by Moini** [zim-desktop-wiki/zim-desktop-wiki#2532]
**Describe the bug**
Unable to install zim from ppa.

**To Reproduce**
1. Add the ppa (https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim) mentioned at https://www.zim-wiki.org/downloads.html to your Ubuntu/Linux Mint package sources.
2. Get error: "W:GPG error: http://ppa.launchpad.net/jaap.karssenberg/zim/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7588B93F8F7DF243, E:The repository 'http://ppa.launchpad.net/jaap.karssenberg/zim/ubuntu jammy InRelease' is not signed."

**Expected behavior**

Repository is signed, package is installable.

**Environment (please complete the following information):**
 - OS: Linux Mint jammy/victoria (but doesn't matter)

**Additional context**
This problem exists for quite a while already, I'm surprised to not see any reports for it. OTOH, I, too, have just commented the ppa out again when I installed zim.

**Comment by prahal** [comment]
How do you add the ppa?
`sudo add-apt-repository ppa:jaap.karssenberg/zim` ?


The key is public and set to never expire (which in my opinion is not good, it should at the very least be limited to 10 years)
https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0xDC4AC0EE92BC64ED020C1C637588B93F8F7DF243
so I do not see how it could be not available.

Can you try `sudo add-apt-repository ppa:jaap.karssenberg/zim` again?

Note I tried on Debian trixie and replacing the distribution in by "noble" and all was fine
```
sudo add-apt-repository ppa:jaap.karssenberg/zim
Repository: 'deb https://ppa.launchpadcontent.net/jaap.karssenberg/zim/ubuntu/ trixie main'
Description:
This is the repository of the stable branch of the Zim Desktop Wiki (http://zim-wiki.org). It builds daily based on commits to the master branch.
More info: https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/jaap_karssenberg-ubuntu-zim-trixie.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/jaap_karssenberg-ubuntu-zim-trixie.list
Adding key to /etc/apt/trusted.gpg.d/jaap_karssenberg-ubuntu-zim.gpg with fingerprint DC4AC0EE92BC64ED020C1C637588B93F8F7DF243
(...)

sudo apt update
(...)
Réception de :16 https://ppa.launchpadcontent.net/jaap.karssenberg/zim/ubuntu noble InRelease [17,5 kB]                                                                                                           
(...)
Réception de :31 https://ppa.launchpadcontent.net/jaap.karssenberg/zim/ubuntu noble/main i386 Packages [540 B]
Réception de :32 https://ppa.launchpadcontent.net/jaap.karssenberg/zim/ubuntu noble/main amd64 Packages [540 B]
Réception de :33 https://ppa.launchpadcontent.net/jaap.karssenberg/zim/ubuntu noble/main Translation-en [588 B]
```

Could you give the full apt output if the issue is still reproducible on your side? and the content of your:
/etc/apt/sources.list.d/jaap_karssenberg-ubuntu-zim-jammy.list

**Comment by Moini** [comment]
@prahal Thanks - I've removed and readded the ppa and it works again. I suppose the signing key has changed at some point.

**Comment by Moini** [comment]
(although the hash is the same... hmmm...)
