### ISSUE TITLE
URL suddenly messed up

### ISSUE THREAD

**Issue by seihtam** [zim-desktop-wiki/zim-desktop-wiki#313]
Version: Zim 0.67 on Windows 10

I had the following URL on a bullet list:
`https://www.reddit.com/r/podcasts/comments/4pajra/post_your_top_5_podcasts/`
It has been there for a long time. I didn't edit the link "Text".

Suddenly the URL looks like this:
`https://www.[[https://www.reddit.com/r/podcasts/comments/4pajra/post_your_top_5_podcasts/|reddit]][[.com/r/podcasts/comments/4pajra/post_your_top_5_podcasts/]]`
If i right click and press "Edit Link" the "Link to" and "Text" sections both contains the string above.

I remember it happening before with other URLs, possible when i was using older versions of Zim, but it seems like a rare bug. The page that contains this URL is one i open frequently. There was other URLs on the same page but it only happened to this one. This was the first URL on the page.

**Comment by jfromero** [comment]
Hi,

I have a similar issue and I think it's related how URL links are copied and pasted. In order to reproduce (in my case)

1. Create a new page
2. Write a URL e.g https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/
3. Select a part of the url e.g https://github.com/jaap-karssenberg/
4. Paste the link in another line
5. It will copy the text but the link will point to the complete URL
6. If you copy a part of the URL in another link it will break it

If you need any other test, just let me know.

Thanks and best regards.

**Comment by synchr** [comment]
I can also reproduce the bug with the steps above.

**Comment by jaap-karssenberg** [comment]
Behavior describe by @jfromero is as designed. If this was the cause of the issue, I don't consider it a bug.

Please re-open if there is another issue behind the mess up.

**Comment by seihtam** [comment]
I still think there is an issue. I found a better way to reproduce it:
1. Paste link
2. Delete part of link (not the whole link)
3. Press Ctrl+z to undo the deleted part of the link
4. Switch to another notebook page and back again

For example deleting "ple.com/" from "http://example.com/", undoing it with ctrl+z and switching page will result in the following text:
http://exam[[http://example.com/|ple.com/]]

**Comment by jaap-karssenberg** [comment]
Dev notes:
  * Issue because links (and tags) are anonymous texttags, after "undo" in the scenario above there are now two anonymous texttags with the same href
  * `insert_parsetree_at_cursor()` should check for merging link (and tag) texttags at start and end of insert range
