### ISSUE TITLE
Window USB Version not seeing new pages after synching

### ISSUE THREAD

**Issue by HeavyTeva** [zim-desktop-wiki/zim-desktop-wiki#371]
Problem occurs when:
- Create a new page running desktop Windows version of Zim.
- Save and Quit Zim
- Sync Zim Notebook folder with USB
- Start USB version of Zim, opening the notebook sync'd to the USB drive. 

The portable version of Zim cannot see the newly created page.  The page (text file) exists in the USB notebook directory, but is not showing in the Zim notebook. 

This does not occur with the desktop version: If I create the new page in Zim USB, save, quit and sync to the desktop Zim notebook directory, then start the desktop version, the desktop version will see the new page on the Zim notebook.

This also occurs for new journal entries:  If I create a new journal entry in Zim desktop, save, quit, sync to USB, then open Zim from the USB, the Journal page does not show in the Index.  However, if I click on the calendar day for the new entry, the new entry is shown.

**Comment by IbanezP** [comment]
hi
I have a similar problem.
I have my zim notebook on a USB and I use it on windows and linux. The problem is that, although the files and folders are the same, the Zim interface doesn't show all the Pages and Sub-pages when switching from one OS to the other (different computers too), even when trying Tools>Update Index.
On windows, I don't remember where I found the trick, but index gets back to normal by deleting a file in the \AppData\Local\Microsoft\Windows\INetCache\zim folder.
I would like to know how to avoid this kind of problem, please...
Thanks for your help
Pab

**Comment by jaap-karssenberg** [comment]
Try running an index update
1. Menu item "Tools->update index"
2. if that fails run "zim.exe --index path/to/notebook"

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
