### ISSUE TITLE
Error trying to delete a page

### ISSUE THREAD

**Issue by banan314** [zim-desktop-wiki/zim-desktop-wiki#420]
I'm trying to delete a page and the following message appears:

**Looks like you found a bug**
```
This is zim 0.68
Platform: posix
Locale: en_US UTF-8
FS encoding: UTF-8
Python: (2, 7, 12, 'final', 0)
Gtk: (2, 24, 30)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 157, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 1095, in delete_page
    DeletePageDialog(self, path).run()
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 2797, in __init__
    text = self._get_file_tree_as_text(dir)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 2824, in _get_file_tree_as_text
    path = child.relpath(self)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 366, in relpath
    names = start.pathnames
AttributeError: 'DeletePageDialog' object has no attribute 'pathnames'
```

I can't delete the page. Neither refresh nor update index nor restarting Zim helps. 

Only thing I can do is to delete the page manually from the disk and refresh Zim.

**Comment by bgutter** [comment]
Same issue here. Originally couldn't delete files due to a failure to create trash directory somewhere in the trash helper code, but disabled that with the hidden notebook.zim setting since I don't want to use trash anyway.

Once that was patched up, I hit the bug in the OP. I tried working around this by replacing:

`child.relpath( self )`

with

`child.relpath( self.path )`

And that allowed me to delete pages..sort of. The page delete dialog claimed that no pages would be removed, but the file was deleted & removed from the gui.

However, deleting a page with subpages will fail with the following:

> This is zim 0.68
Platform: posix
Locale: en_US UTF-8
FS encoding: UTF-8
Python: (2, 7, 14, 'final', 0)
Gtk: (2, 24, 32)
Pygtk: (2, 24, 0)
No bzr version-info found

>======= Traceback =======
  File "/usr/lib/python2.7/site-packages/zim/actions.py", line 157, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python2.7/site-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zim/gui/__init__.py", line 1095, in delete_page
    DeletePageDialog(self, path).run()
  File "/usr/lib/python2.7/site-packages/zim/gui/__init__.py", line 2797, in __init__
    text = self._get_file_tree_as_text(dir)
  File "/usr/lib/python2.7/site-packages/zim/gui/__init__.py", line 2824, in _get_file_tree_as_text
    path = child.relpath(self.path)
  File "/usr/lib/python2.7/site-packages/zim/newfs/base.py", line 366, in relpath
    names = start.pathnames
AttributeError: 'PageIndexRecord' object has no attribute 'pathnames'

...which leads me to believe that the fix may be a little more than I expected.

**Comment by WolfPDCB** [comment]
I think I have the same issue, too. Below is the information obtained from Zim on my computer:

> This is zim 0.68-rc1
> Platform: posix
> Locale: en_US UTF-8
> FS encoding: UTF-8
> Python: (2, 7, 15, 'candidate', 1)
> Gtk: (2, 24, 32)
> Pygtk: (2, 24, 0)
> No bzr version-info found
> 
> ======= Traceback =======
>   File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 157, in do_activate
>     self.__get__(instance, instance.__class__)()
>   File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
>     self.func(instance, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 1095, in delete_page
>     DeletePageDialog(self, path).run()
>   File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 2797, in __init__
>     text = self._get_file_tree_as_text(dir)
>   File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 2824, in _get_file_tree_as_text
>     path = child.relpath(self)
>   File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 366, in relpath
>     names = start.pathnames
> AttributeError: 'DeletePageDialog' object has no attribute 'pathnames'
>

**Comment by WolfPDCB** [comment]
Run into this issue again. This time the page contains attached link to documents. It seems like Zim has trouble deleting pages with attached image or file links.
