### ISSUE TITLE
Suggestion: "Column Select" feature

### ISSUE THREAD

**Issue by shnbwmn** [zim-desktop-wiki/zim-desktop-wiki#463]
G'day :)

There is already a "Sort lines" plugin which I find very useful, however another frequent task I perform is prefixing characters to a column of words/phrases (like adding +'s to a bunch of words to create subpages). I know I can edit the source in a text editor from within Zim, but like line-sorting, it would be great to have this functionality within the editor. 

Basically like Notepad++/Notepad2-mod column-select (Alt-Select) would be great. I don't think it would be such a hassle? :)

Regards

**Comment by jaap-karssenberg** [comment]
Afraid this is a "won't fix" because the underlying Gtk widget does not support multiple cursors, so would be a rather big hack to make it work.

I suggest you may want to use the "edit source" option for more advanced text editing. Or you could even automate common actions using a script as a "custom tool".
