### ISSUE TITLE
Beter detect multi-line verbatim blocks

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#49]
See https://bugs.launchpad.net/zim/+bug/1173609 for a conrete error

Also think about verbatim that starts out as inline, then by editing ends up as full line verbatim - convert to block automatically.

And vice-versa, if block is broken up in segments convert to inline format.

Overall make sure that the user does not need to know the difference between verbatim block and inline verbatim.

**Comment by jaap-karssenberg** [comment]
See https://bugs.launchpad.net/zim/+bug/1363556 for second example

**Comment by vossenjp** [comment]
https://bugs.launchpad.net/zim/+bug/1363556/comments/3 is interesting.  I often have a bullet or Checkbox list of commands, and I want to hit CTRL-T to make them "code" so the end result is: `* ''cmd''` which is what I get.  But when I do that long lines do not wrap, which makes them unreadable.  When I then re-apply CTRL-K for a checkbox, the lines then wrap.  When I re-apply using CTRL-L for a bullet list, they do *not* wrap.  Yet the markup is the same and as expected: `* ''cmd''` or `[ ] ''cmd''`.  Perhaps there's a difference in the rendering due to the bullet vs. the check box?

**Comment by jaap-karssenberg** [comment]
* Start with test cases to capture the behavior

**Comment by jaap-karssenberg** [comment]
Seems behavior reported above has improved by simplifying the rules for verbatim versus code formatting.
Also the new "paste as verbatim" should help in these use cases.
Will add few test cases to make sure it doesn't break again.
