### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by prog20901** [zim-desktop-wiki/zim-desktop-wiki#530]
1. type ahead search, 
2. number of hits 
3. auto-complete suggestion 
4. faster search when we have 2,00,000 pages or contents being saved
5. easy navigation between the next hit found
6. preview of the text with paragraph
7. highlight the entered keyword in the page which is being saved

**Comment by hikmatsp** [comment]
If I may add other request for enhancements,

1. Themed Window/Pane customization, like in Cherrytree.

![cherrytree](https://user-images.githubusercontent.com/6463767/46061546-41040000-c191-11e8-962a-ce383159bb4d.png)
_Caption: This Cherrytree window is a not its default theme, but after some easy tweaking, it looks like what I wanted to view._

I know ZimDesktop is powerful already and I am grateful for this. I know it because I've been using Zim for about 3 years. But if you could make Zim mimicking Cherrytree pane customization, it would be awesome. 

2. Thank you so much in advance.

**Comment by Osndok** [comment]
> Did you get a chance to work on this ???

Who are you addressing? Do you have a servant or employee watching this ticket?

AFAIK, we are all volunteers here, and the purpose of the issue tracking system is for **you** to be able to help (in some small way) to organizing defects and feature request, not to make demands.

A little more advice, to help you out:
1. in general, there should only be one well-described issue per ticket (not a terse outline of unrelated things)
2. before filing a ticket, you really should do the curtoesy of trying a 'search' to be sure the particular issue has not already been reported (and, instead, helping with that ticket instead of creating noise). For example, your point number 4 aligns well with the existing ticket #64 
3. you should have a descriptive title for the (again, singular) issue... not so broad and vague as "enhancement"... I might suggest that each of your outline items might be more useful as a title.

**Comment by jaap-karssenberg** [comment]
Closing this ticket because it is very broad and not specific on the requested items.
