### ISSUE TITLE
Renaming a page breaks links

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#549]
1. Create Zim:Examples:Linking:Relative
2. Write something in "Relative", select the text and link it to "Absolute", by writing "Absolute"
3. Follow the link to "Absolute" and write there something, so that this page gets permanent
4. Go back to "Relative", write something, select the text and link it to "Examples:Calendar" by writing "Examples:Calendar"
5. Follow the link and write something in "Examples:Calendar" to make this page permanent
6. Rename "Examples" f.i. to "ExamplesRENAMED", normally with F2 (both checkboxes should be enabled), and you'll see that "Absolute" and "Calendar" are now greyed out in the side panel, because both links in "Relative" now link to "Zim:ExamplesRENAMED:Relative:Absolute" and "Zim:ExamplesRENAMED:Relative:Examples:Calendar", thus destroying the linking and creating ghost pages

IMHO, it's a critical bug, since it's already destroyed a lot of links in my wiki.

Happens on Ubuntu 18.10 with Zim v0.68 from the official repository.

**Comment by Osndok** [comment]
Thank you for writing out this test vector! I meant to do so, some time ago, in order to demonstrate this to Jaap, but I guess I never got around to actually coming up with one.

What's more, it is not just renaming that causes breakage. AFAIK... floating links (aka "relative links") **can also be broken due to a page being moved, or even a page being created.**

To be clear:
* I too, have experienced this bug
* I too, would classify this even as a critical as a **"data loss bug".** Even if it is for such a small unit of data/effort that is lost, it can generate a lot of confusion (esp. for the backlinks that are simply 'missing') and frustation/nuisance.

After considering "the issue" with how floating links (aka "relative links") are resolved, the only way I see to save the concept of floating links (aka relative links) is to attach them by uuid before name/path, but the zim markup is not really geared for that so it would be a lot of work and maybe even a bit of rearchitecting how links are rendered and maintained.

So until then, I have suggested #492 to have zim **not automatically suggest/create this somewhat-dangerous form of links**, a pull request which you might be interested in.
