### ISSUE TITLE
Add more maintainers to alleviate 300+ issues and pull requests from 2017

### ISSUE THREAD

**Issue by farisachugthai** [zim-desktop-wiki/zim-desktop-wiki#582]
I, as I'm sure most are, am a huge fan of Zim and have been using it for my daily note taking app for years.

However, the number of issues in the repository are piling up. The wiki hasn't been updated in months, and issues that were created in September haven't seen any response yet.

@jaap-karssenberg, I totally understand that sometimes life gets in the way. 
You don't owe us all of your free time. 

But your project has gotten large enough that maybe it's time to start offshoring a little bit of the work and get more maintainers and people with commit rights in order to keep the pipeline flowing. 
At the time of writing, there are currently 35 open pull requests, and at a cursory glance, most don't conflict with master at all.

One has integration with matplotlib which would be an incredible functionality!

Others are spelling mistakes and things that should merge quickly.

So I'm asking you to please keep this project going and get more people to help.

**Comment by jaap-karssenberg** [comment]
@farisachugthai I would love to have more maintainers help out. Unfortunately I don't know which persons to invite. Since zim is overdue for porting to puthon3 / Gtk3 I have been working on the "next" branch since  last februari. I have asked for help on that undertaking on the mailing list. Unfortunately my requests went largely unanswered. Ignoring the current open issues and open merge requests is the only way I can get progress with the port. Will merge "next" back into "master" to make more visible the conflicts that arise by now accepting more patches on the gtk2 branch.
