### ISSUE TITLE
Is it possible to add brackets in pages name ?

### ISSUE THREAD

**Issue by seigneurfuo** [zim-desktop-wiki/zim-desktop-wiki#597]
Hello.

I use Zim in an particular case and I want to know if is it possible to use bracket, particulaly this one [ in pages name ?

If not, where in the code can I find a "replacement table" or where can I add the support for custom characters ?

Thanks.

**Comment by Self-Perfection** [comment]
In my experience zim refuses to create page if its name starts with square bracket.

**Comment by seigneurfuo** [comment]
@Self-Perfection Same behaviour for me.

**Comment by seigneurfuo** [comment]
@nelas 
Here is my "particular case":
I use Zim on existing directory who already contains folders. Each folder is dedicated to a specific project already contains files (python code or other). When I want to add a documentation to a project, I manually add a Zim page.

And Zim will only show his files on the notebook, and I have all of my documentation in a single place (cause non zim files are ignored).

This method work fine with folders without brackets.
But I can't use this method with folders that countains brackets.

**Comment by nelas** [comment]
Ah, I see now what you mean @seigneurfuo. Indeed I can reproduce what @Self-Perfection described. If the page name starts with a square bracket, this bracket will be stripped off the page name. The page itself is still created, but without the first bracket.

Thus, `[yyyy.mm.dd] Project Name` becomes `yyyy.mm.dd] Project Name`.

I check a bit and this seems to happen because Zim does not allow non-alphanumeric characters (or underscores) in the first character of page names. This part of the code is here:

https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/6645b6ca9652d1a97be1b9d08481ddd2e2ce6616/zim/notebook/page.py#L28

Even though square brackets are not explicitly documented as forbidden characters in the documentation (these are "?", "#", "/", "\\", "*", '"', "<", ">", "|" and "%" - see `Help:Pages`), there might be a reason why the brackets are also being stripped off (e.g. compatibility with all OSes). Only @jaap-karssenberg can say :)

Replacing the string above by `'^[^a-zA-Z0-9_\[]|(?<=:)[^a-zA-Z0-9_\[]'` would allow `[` and `_` to be used as starting characters in page names. But this might break something in the Zim internals... so I would recommend waiting for Jaap's take on this.

Cheers

**Comment by Osndok** [comment]
The square brackets are used to designate page links, so I would expect there to be parsing issues (or at least, unexplored edge cases) as they would have to be used inside other square brackets.

e.g. ```[[MyPageWith[BracketedPart]]]```

**Comment by jaap-karssenberg** [comment]
Limitations are in the manual here: http://zim-wiki.org/manual/Help/Importing_external_files.html

Additional limitation is that the first character of a page name needs to be alphanumeric and not a special character.
