### ISSUE TITLE
Page names in the pathbar look bulky

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#617]
As shown [here](https://i.imgur.com/xa5gvOE.png), they look too bulky and should have more spacing. The same goes for selected tags in the tag cloud, when they are selected.

**Comment by jaap-karssenberg** [comment]
They are normal buttons. Afraid rendering depends on theme settings, so may look different for different people.  Probably possible to improve using the CSS styling of Gtk3, but low prio item for me.

**Comment by vossenjp** [comment]
I was going to say the opposite here.  After upgrading from Zim 0.69.1 to 0.70, my bookmark and path bars are now almost worthless, because the buttons have too much margin (wasted space) on both sides of the text, so they are now too large.  So now they don't fit without scrolling, with makes them just about useless.

**Comment by sojusnik** [comment]
@vossenjp A picture would help.

**Comment by vossenjp** [comment]
How about some ASCII art?
Older than 0.70 my Bookmark bar looks like this **and all of it fit on my screen** (note no scroll < > indicators):
```
[Index][ToC]  |+ [3 Customers][Git][Ansible][Xxxxx][4 Ref][2 People][Project][XxxxxXXX][1 Con Calls][1 Work]
-----------------|[ ...Various buttons for Path bar here ...]
...sidebar...    |
```

Since 0.70 it looks like this and **does not** fit on my screen, it scrolls, which makes it a lot less useful
```
[Index][ToC]  | < [ ...Various buttons for Path bar here; note reversed! ...]
-----------------|+ < [ Ansible ][ Xxxxx ][ 4 Ref ][ 2 People ][ Project ][ XxxxxXXX ][ 1 Con Calls ][ 1 Work ]
...sidebar...    |
```

As I look at that, when scrolled all the way to the right only the two left-most buttons are cut off, which is less than it seemed.  So < 0.70 had the Bookmark bar on top and the path bar under it, but with 0.70 that reversed.  I don't see any way to change it, and I don't really care.  But since the bookmark bar is now directly to the right of the ToC instead above and to the right, it's a bit shorter.  So I think the button padding is just a bit more and the bar is just a bit shorter, but the end result for me is less utility because of scrolling.  I could probably "fix" that by renaming some pages with shorter names, but I'd rather not.

Note the `[Index][ToC]` buttons do *not* have the extra padding, they look like they always did.

Possible ways to fix this for both bookmark and path bars:
1. Reduce spaces/padding to the left and right of the text/labels in the buttons
	* Like the `[Index][ToC]` buttons?
2. Make the font for the labels adjustable

**Comment by Xunius** [comment]
Can we make the texts in the path bar and bookmark bar buttons elided if the length go beyond a limit? Some of my notes have pretty long titles and the path bar button would take up the entire window width, and you can't resize the window down anymore because of this.

**Comment by jaap-karssenberg** [comment]
Please see commit 1ae754573e42b5d899ee82e1fc02b047303a1fa7 for improvements on the pathbar style. 

(If you run the snapshot PPA it will turn up in the next day or so)

**Comment by vossenjp** [comment]
This now looks great in 0.72.0, thanks!
