### ISSUE TITLE
Spellcheck correction removes formatting

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#62]
See https://bugs.launchpad.net/zim/+bug/691273

Solution probably requires wrapping the menu items for the spellchecker to detect changes and and re-apply the formatting.

**Comment by vossenjp** [comment]
This is a big problem for me because I'm a terrible speller, and I experience it more as adding unwanted newlines.  The main problem there is that the lose of formatting and/or unwanted newlines are invisible until a page refresh, or leaving/returning to the page, or a copy&paste out.  That means it screws up invisibly, until later.  For me this is so bad I use the spellcheck only to show me what I got wrong, then I correct it manually or using another tool.  :-(

**Comment by jaap-karssenberg** [comment]
Committed fix to development branch. At least applies to gtkspellcheck, did not test for gtkspell
