### ISSUE TITLE
make images scale with text on zoom

### ISSUE THREAD

**Issue by mechadense** [zim-desktop-wiki/zim-desktop-wiki#65]
When hitting Strg++ or Strg+- only the text scales.
Images stay constant in size.
Individual image re-scaling via the dropdown is impractical for e.g. presentations.

**Comment by jaap-karssenberg** [comment]
Considering this item a "won't fix". To scale the content e.g. in presentation mode, my suggestion would be to use the "print to browser" option and use the html view for presenting.

See #324 for intended fix to make large images fit in the view, which is kind of an opposite use case, but might help here as well because the intention is to scale dynamically to the size of the window.
