### ISSUE TITLE
File links containing "|" are truncated and break

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#660]
To reproduce, create a file containing `|` (f.i. `~/test|ing.txt`) in your file browser (mine is nautilus). Right-click on the file and press copy. Now paste the path into a page within Zim. Refresh and you'll see that only the part after `|` is shown. The link is broken too.

Happens with v0.70-rc2 on Ubuntu 18.10.

**Comment by Osndok** [comment]
This is not really a bug so much as a limitation of the zim markup language, because the vertical pipe is used to separate the link-proper from the displayed text.

e.g.
```[[:Some:Other:Page|Click Me!]]```
```[[https://apple.com|Apple Computer]]```

As a side note, the piping symbol is a pretty bad character to put in a file name to begin with. You would also have trouble using that file name in the shell, for example.

**Comment by sojusnik** [comment]
Thanks, Osndok! My bad, should have checked this before.
