### ISSUE TITLE
[enhancement] Support editing multiple notes at the same time

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#689]
Imagine that you send an email to a group of people, each one is a single note in zim.
I'd love to be able to multi-select their notes and say add a line to all docs, with 'emailed <today>'.

Is this in any form interesting for anyone else?

**Comment by Osndok** [comment]
The provided title makes this request **sounds** a bit too much like #153 or #267... perhaps a better title would be to "**append to several pages at one time**" (i.e. 'append' rather than 'edit').

> Is this in any form interesting for anyone else?

I have a few scripts which do similar operations from the command line, so on the surface it seems like a perfectly reasonable and helpful feature.

AFAIK, we do not currently have any multi-page operations, so this would be a first. I could see it being the first entry in a **context menu**... and there are probably other context menu operations that could be applied to multiple pages (move, delete, bookmark, search, maybe even copy-link).

For my use, it seems that my notebooks get big too fast, or more accurately... it seems that **the index pane becomes unwieldy so quickly** (as the notebook size increases) that I don't expect this to be useful except for very small notebooks... and I'm not sure if it would play will with my ideas for how to increase the effectiveness of the index panel for large notebooks (e.g. https://bugs.launchpad.net/zim/+bug/1687119 - a rolodex-style index pane).

**Comment by jaap-karssenberg** [comment]
THis is a "Won't Fix" for me. Of course you can try out different scripts to do this as a custom tool.
