### ISSUE TITLE
menubar and toolbar dissappeared after distraction free editing

### ISSUE THREAD

**Issue by bkilinc** [zim-desktop-wiki/zim-desktop-wiki#724]
I use version 0.70 on linux mint 18. After distraction free editing; menubar and toolbar is lost. I cannot show them back.

**Comment by jaap-karssenberg** [comment]
This could happen is an error occurs on switching back - would be good to
see that error log to fix it.

To reset check the "State.conf" file for the notebook (either in
notebook/.zim or in ~/.cache/zim/notebook folder) this will store the
menubar and statusbar visibility.

-- Jaap

**Comment by bkilinc** [comment]
After deleting the cache files zim works perfect. Thanks for support and for great software.  
I guess this problem is reproducible after an upgrade. It happened in two of my computers. But is not reproducible anymore (after deleting cache files).

**Comment by jaap-karssenberg** [comment]
Re-opened because this needs more robust error handling

**Comment by mikro2nd** [comment]
More information in case it helps: (Zim 0.70, Kubuntu 18.10)
Switching to fullscreen and back again loses the menubar consistently. Exiting zim completely and restarting restores the menubar -- menubar and toolbar are both enabled in state.conf -- but since I usually live with zim running in the system tray that's less than ideal. 

I don't find it necessary to clear cache every time -- only the first time was necessary.

Also: Pathbar is now visible in fullscreen mode. Was this an intentional change? Could it be disabled via an option? For me it's quite a bad distraction to have visible in "distraction free mode". ;)

**Comment by mikro2nd** [comment]
Can we please re-open this bug -- still a problem in 0.72.0 even after clearing the cache directory. Steps to reproduce:
* Exit zim completely.
* rm -rf ~/.cache/zim/*
* Restart zim. (Window sizes are lost, but no big deal. Toolbar and status bar are visible.)
* F11. Fullscreen mode works as expected.
* F11. Back to windowed mode, toolbar and status bar are gone, and great amounts of excess filler-space around the edit pane. `In state.conf` I now have
    show_toolbar=False
    show_statusbar=False

HTH. Ping me if there are more ways I can test to nail this thing down.
