### ISSUE TITLE
Cannot switch-on zeitgeist plugin

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#787]
Xubuntu 18.10
Zim 0.70 snapshot 11.04.2019
libzeitgeist
python-zeitgeist

But I cannot switch-on zeitgeist plugin in plugins-list in options.

I see:
• libzeitgeist - Error (Дополнительно)

**Comment by jaap-karssenberg** [comment]
Not using zeitgeist myself, so needs investigation by someone who does

**Comment by mstimberg** [comment]
I haven't used the plugin myself in a while, but at least part of the problem is that `python-zeitgeist` provides the Python bindings for Python 2 and not for Python 3 (as used by zim). From this [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781909), it seems as if a `python3-zeitgeist` package now exists but I did not find it in Debian's package repository. The alternative (and more long-term solution) would be to make the plugin use the GObject introspecting bindings from the `gir1.2-zeitgeist-2.0` package, but I'll need to have a closer look into this.

**Comment by introt** [comment]
Nowadays, with Zim 0.74.0 on Xubuntu 21.04, the plugin loads using `python3-zeitgeist` but throws `TypeError: on_page_changed() takes 2 positional arguments but 3 were given ` and seems to fail silently on other signals. For little more context see [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1609#discussioncomment-1373552)

**Comment by jaap-karssenberg** [comment]
Probably a topic for the discussion forum: is this plugin / this Gnome
feature still relevant, or could we remove it from the package ?

**Comment by mstimberg** [comment]
As far as I can tell, `zeitgeist` and the affiliated "[Gnome Activity Journal](https://wiki.gnome.org/Apps/ActivityJournal)" are still actively developed (e.g. the latter is included in Ubuntu 21.04). So I guess it would still make sense to support the integration via a plugin.
I will have a look whether the necessary changes are straightforward with the `python3-zeitgeist` package or whether this would require a lot of work.
