### ISSUE TITLE
spell check plugin can not be configured

### ISSUE THREAD

**Issue by g1ocke** [zim-desktop-wiki/zim-desktop-wiki#817]
I use Zim flatpak from Flathub, unfortunately, the spell check plugin can not be configured, the button is greyed out...

![56737148-0fc0d200-676a-11e9-85cb-c23c0cad4cd1](https://user-images.githubusercontent.com/14040247/56940439-c3c9b080-6b0e-11e9-95aa-ce2c7ed7a08d.png)

**Comment by g1ocke** [comment]
and the icon will not be displayed after activation...

![56738653-5106b100-676d-11e9-877f-e75cd0f63205](https://user-images.githubusercontent.com/14040247/56940528-67b35c00-6b0f-11e9-936d-b38883544c88.png)

**Comment by jaap-karssenberg** [comment]
The spellcheck plugin does not have configuration, so the button is greyed
out on purpose. To set the language, go to the properties dialog (File
menu).

The spellcheck is no longer available in the toolbar. This is due to how
the menus and toolbar are now build dynamically. You should find it in the
menu, and be able to use F7 to toggle.

If you find it really doesn't work, please run "zim --debug" and check for
error messages when the plugin is loaded.

Regards,

Jaap

**Comment by g1ocke** [comment]
ok, and how can I set the default language?

**Comment by g1ocke** [comment]
DEBUG: Load extension: <class 'zim.plugins.spell.SpellPageViewExtension'>
DEBUG: Spellcheck language: en_US
DEBUG: requesting name for code "en_ZA"
DEBUG: requesting name for code "en_IE"
DEBUG: requesting name for code "de_AT"
DEBUG: requesting name for code "en_NZ"
DEBUG: requesting name for code "en_NA"
DEBUG: requesting name for code "en_BZ"
DEBUG: requesting name for code "en_US"
DEBUG: requesting name for code "en_IN"
DEBUG: requesting name for code "en_JM"
DEBUG: requesting name for code "en_TT"
DEBUG: requesting name for code "en_CA"
DEBUG: requesting name for code "en_PH"
DEBUG: requesting name for code "en_ZW"
DEBUG: requesting name for code "en_GB"
DEBUG: requesting name for code "de_DE"
DEBUG: requesting name for code "de_CH"
DEBUG: requesting name for code "en_MW"
DEBUG: requesting name for code "en_GH"
DEBUG: requesting name for code "en_AU"
DEBUG: requesting name for code "en_BS"

**Comment by sojusnik** [comment]
@g1ocke see https://i.imgur.com/ePpPG5U.png

**Comment by g1ocke** [comment]
great, very good ... thanks!
