### ISSUE TITLE
A page with a "ß" in its name isn't found

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#84]
When a page name has a "ß" in its name, then "go to" (Ctrl+J) doesn't find that page.
Observed under v0.66 from the snapshots repository.

**Comment by jaap-karssenberg** [comment]
Testing with my 0.67-rc1 snapshot I don't observe the same issue

**Comment by sojusnik** [comment]
Create a "Maßnahmen" page. Then open the "go to" window (normally Ctrl+J) and type "Ma". At first you'll see that page, but when writing "Maß" the page will disappear.
Happens with the latest v0.66 from the snapshots ppa.

**Comment by jaap-karssenberg** [comment]
Something weird going on here. Tested on windows system and there it works correctly. But on my linux system it doesn't. One level deeper the matching function gets passed "mass" instead of "maß", so somewhere in the library it is being more intelligent than it should. No idea if this is input method related, locale related, or something else.

**Comment by sojusnik** [comment]
With v0.70 this happens also to page titles containing umlauts like ö etc.

Observed on Ubuntu 18.10

**Comment by mexicarne** [comment]
Works perfectly fine here in 0.70-rc3. The same with umlauts.

**Comment by jhakonen** [comment]
I found a way to fix this.

The `key` in `gtk_entry_completion_match_func` is utf8 normalized and casefolded. This is described in documentation: https://lazka.github.io/pgi-docs/Gtk-3.0/callbacks.html#Gtk.EntryCompletionMatchFunc

So, there's two possible ways to fix this (as mentioned in the documentation):
1. Instead of using `key` retrieve the key value from the entry using `get_text()`. That value is not normalized/casefolded and can be compared against `text`.
2. Normalize and casefold the `text` variable and then compare it and the `key`. At comparison the `.lower()` is not needed due of the `text` being already casefolded. Right arguments for normalizing and casefolding I checked from GTK's sources: https://github.com/GNOME/gtk/blob/3.24.4/gtk/gtkentrycompletion.c#L1290

Here's the two different options as patches:
https://gist.github.com/jhakonen/88a8e96ddaa4adf0fb558416dec919c4

I'm not sure which one you think is better, so I didn't do PR. 

Tried with pages "Tärkeä" and "Maßnahmen" using Ubuntu 18.10.

**Comment by jaap-karssenberg** [comment]
@jhakonen thanks for the patch!  I figured out the same once I realized it was driven by accents, but haven't had the time create a patch yet.

No preference on my side - as I have no clue whether there would be difference in performance - so feel free to open a PR and I'll merge it.

**Comment by jhakonen** [comment]
Ok, cool I'll make a PR then.

I tried writing tests for this, but it seems that the match funcs are quite impossible to test, at least in conjunction with the PageEntry. They filter a Gtk.TreeModelFilter, but it is not exposed from Gtk.EntryCompletion, so can't access the filtered data from tests :(

**Comment by jhakonen** [comment]
I'll take back what I said about the tests. I found somewhat roundabout way to get the filtered completion model. Just have to recursively walk through all top level windows, their children, and their children... and so on, until you find the Gtk.TreeView that is used to render the completion popup. The view has a method for getting the filtered model.
