### ISSUE TITLE
plugin trayicon not working

### ISSUE THREAD

**Issue by gutierri** [zim-desktop-wiki/zim-desktop-wiki#896]
The trayicon plugin does not work, when you get the command line it generates an error by not finding the icon.

```sh
~ % zim --plugin trayicon
WARNING: Could not find all icon sizes for the application icon
```

```sh
~ % zim --version
zim 0.71.1
```

**Comment by gutierri** [comment]
Update: issue only wayland.

**Comment by msnjuegos** [comment]
I have the same problem. I have updated zim from 0.68 to 0.72 in Debian 10 with Wayland and the trayicon plugin is not working now.

**Comment by hbozhkov** [comment]
For both the latest version of Zim, as well as the one available in the repos for Ubuntu 20.04, the tray icon plugin does not work both with the classic and indicator sys tray icons and running it from the terminal returns the same response :<pre><font color="#3465A4"><b>~</b></font>$ zim --plugin trayicon
WARNING: Could not find all icon sizes for the application icon
</pre>
I'm using X, not Wayland. Anyone figured it out?

**Comment by jahnf** [comment]
For me on Ubuntu 20.04 after installing `gir1.2-appindicator3-0.1` the tray icon worked.

**Comment by nbCloud91** [comment]
This problem is present in version 0.75.1 on NixOS-unstable (Under GNOME-Wayland), but it works all right in Ubuntu 22.04 LTS.
On NixOS I get the same warning as the OP.
```
~ % zim --plugin trayicon
WARNING: Could not find all icon sizes for the application icon
```
I even added libayatanaindicator and libappindicator-gtk3 to the build-inputs to nix-ovelay script for bulding zim like so:
```
self: super:

{
  zim = super.zim // {
    buildInputs = super.zim.buildInputs ++ [self.libayatana self.libappindicator-gtk3];
  };
}
```
But tray icon still doesn't work. Also, the default path of the panel icons being in ubuntu-mono-dark or ubuntu-mono-light subdirectory may be an issue. All GNOME users are not using ubuntu, maybe it would be better to use the default "hicolor" path for icons?
cc @introt

**Comment by introt** [comment]
> Also, the default path of the panel icons being in ubuntu-mono-dark or ubuntu-mono-light subdirectory may be an issue. All GNOME users are not using ubuntu, maybe it would be better to use the default "hicolor" path for icons?

Please open a new issue for this, thanks!
