### ISSUE TITLE
Make indexer ignore text files that are not zim pages

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#907]
Make indexer ignore text files that are not zim pages. This requires checking the file headers in the page indexer. Any `.txt` file that does not have headers should be treated as an attachment.

Test
- behavior when trying to create a page of the same name 
- behavior when trying to move to a page of the same name
- behavior when trying to import the file as a page

Maybe need some kind of dialog to find such files and allow (batch) importing them. Or put the option to import somewhere in the interface when trying to access them. One way to do so is to allow plain text pages without formatting.

**Comment by hasan-sh** [comment]
I got a god notebook and subnotebooks, when I export and convert all notebooks to Html, it copies every single file in that god notebook directory, even if it doesn't contain a subnotebook! I think it's related to this!

Any updates?

**Comment by amanda1981** [comment]
Is this fixable I dont know what iam doing

**Comment by krisztianmukli** [comment]
I'm storing some hundred gigabytes in a folder which contains Zim notebooks. Previously I used a main notebook which has subnotebooks, but is causing some problems, and I think it doesn't have any meaning, because notebooks can linking each others, so this time I'm using separate notebooks in my Documents folder. My Documents synchronizing with my Nextcloud server. 

Previously I have problems with huge amount of files, because when I'm storing files in a hidden folder, Zim can't see them, but indexer of Zim can access them. And of course sometimes would be helpful if I can regulate which folders synchronizing and which are not in Nextcloud, without a huge and always changing exclude list.

My temporary workaround is for files what I would like to hide before the indexer, storing in a folder which has a name starting or ending with a "~". 

If a folder starting with "~" is hiding only before Zim and it's indexer (Zim can't read and display them), but not hiding from Nextcloud (it's synchronizing).

If a folder name ends with "~" it is hidden from Zim and Nextcloud. It is a standard for naming backup files and folders (for example in Bleachbit must add there to the exclude list, if you use it). It won't be synchronized with Nextcloud (there are in default exclude list: *~). These files won't display in Zim and it's cache. It can't attaching in Zim, but you can create links for files manually. I can storing files in the project's folder without Zim indexing files for hours.

Yes it a very ugly use-case, but I think it is a usable workaround until this feature will be ready. What's happen when export and convert to HTML? I don't know, I never try it! :-)

Example (folder's name starts with /):
```
/Documents
├── /Notebook 1
│	├── Home.txt
│	├── /Home
│	│	└── Subpage.txt
│	└── Page.txt
│
└── Notebook 2
 	├── Home.txt
 	├── /Home
 	│	├── /01
        │      └── 01.txt
 	├── Project.txt
  	├──/Project
        │    └──/~Source code <= Hidden from Zim
        │            └── ...Lot's of small files...
 	├──Another Project.txt
 	└──/Another Project
               └──/Church records~ <= Hidden before Zim and Nextcloud
                       └── ...Lot's of big files...
```

**Comment by BehindTheBrain** [comment]
@krisztianmukli #472 has a workaround that is easy and a total fix. I've been using for a couple years with many gigs of zim notebooks.

**Comment by K-C-Martin** [comment]
I think this might have broken my workflow: I often create new txt files as via my Dropbox Android app, saving them in Zim folders so I can access them in the wiki later... I recently discovered that a bunch of pages were not indexed (until I opened them and pasted in the wiki header line).

Is there an option to allow indexing plain text files again?

Thank you for a great tool.

**Comment by introt** [comment]
@K-C-Martin an alternative is to use the free & open source Markor text editor, which supports the Zim Wiki format and syncing via Dropbox

https://github.com/gsantner/markor

**Comment by jaap-karssenberg** [comment]
Current behavior is that when you try to open a page of the same name as
the non-indexed text file you get a pop-up whether you want to import the
file. This import will add the headers for you.

What is currently missing is a "batch import" - some kind of tool that
gives a list of all non-indexed text files and allows to select one or more
for import.

--- Jaap

**Comment by e3rd** [comment]
For a future reference, this line will identify all TXT files that were not yet imported and remain invisible in the Zim index.

`find . -type f -name "*.txt" -exec awk 'NR==1 && !/^Content-Type/ {print FILENAME}' {} \;`

And this one will prepend the Zim header to all such files so that they are indexable (creation-date will be picked from the file modified time):

`find .  -type f -name "*.txt" -exec sh -c 'if ! head -n 1 "$1" | grep -q "^Content-Type"; then mtime=$(stat -c %Y "$1"); sed -i "1iContent-Type: text/x-zim-wiki\nWiki-Format: zim 0.6\nCreation-Date: $(date -d @$mtime --rfc-3339=seconds)\n" "$1"; fi' _ {} \;`

**Comment by meldridge** [comment]
> I think this might have broken my workflow: I often create new txt files as via my Dropbox Android app, saving them in Zim folders so I can access them in the wiki later... I recently discovered that a bunch of pages were not indexed (until I opened them and pasted in the wiki header line).
> 
> Is there an option to allow indexing plain text files again?
> 
> Thank you for a great tool.

@K-C-Martin did you ever solve this? I'm in the same situation - I store random text files throughout my notebook folder structure and I like to have them all indexed, whether or not they're Zim-format.

**Comment by K-C-Martin** [comment]
I actually haven't used Zim Wiki for a long time - I hope you're able to find a fix that works for you.

**Comment by meldridge** [comment]
Damn. Thanks anyway. What did you switch to, if you don't mind me asking?

**Comment by jaap-karssenberg** [comment]
@meldridge you can import text files and turn them into pages. One way is to use the "import" menu item. Or navigate to the page of the same name and you will be prompted. The otehr way is from the commandline. There is a snippet above that does this. In the repository there is a patch to add commandline switches to zim as well for this (not yet in latest release, but available from source).
 
Hope this helps

**Comment by meldridge** [comment]
Thanks @jaap-karssenberg, that's not what I'm looking for though. I don't want to convert existing .txt files into pages, I just want any text file in the notebook directory to be visible in Zim, whether it's a Zim-formatted .txt or plain text .txt.
