### ISSUE TITLE
(Daring) thoughts on a re-implementation

### ISSUE THREAD

**Issue by fmos** [zim-desktop-wiki/zim-desktop-wiki#986]
(This is a non-issue and really meant as a discussion and probing for common interests.)

Packaging for Windows (see #639 ) and MacOS is practically non-existent. It seems that is due to the difficulty of packaging Python 3 and GTK 3 and due to the state of the bindings between these components. 

What if Zim was re-implemented in a compiled language (e.g. C++) and a toolkit receiving more cross-platform attention (e.g. Qt)? Is that even possible? Is it feasible? Would it improve the situation? How could one approach such an endeavor? What would be needed? 

What are your thoughts? Maybe collecting and documenting them here will be useful in any case. Even if the result confirms the decision to stick with Python and GTK.

**Comment by jaap-karssenberg** [comment]
Hi Fabian,

In my opinion you mistake a people issue for a technical issue. The lack of
packaging for windows or OS X has little to do with technical challenges.
It is because there are no volunteers seriously looking into in. At least
for the windows packaging I found very decent approaches just searching the
internet for solutions for a night or two. However, since I already have
too little time to do new feature integration, I leave the packaging to
others. As long as nobody steps up and looks into it, nothing happens
there.

I do not think this has anything to do with fundamental issues or
limitations of either Python or Gtk. Making python and Gtk work on windows
and OS X probably takes only a fraction of the time you will need to spent
to re-implement the entire code base. And re-implementing in another
language and/or using a different toolkit will solve some issues, but in
the long run it will run into other issues that you will not foresee
upfront as each language and toolkit has it's strengths and it's weaknesses.

Kind regards,

Jaap

**Comment by fmos** [comment]
Thank you for your reply! I don't think this is an either-or question. Rather, I guess the technical challenges are part of the reason for the "people issue". At least for myself, when 0.70 was released, I have tried several evenings to package this release for macOS. I couldn't find a way even for my own use and eventually gave up after three or four evenings. Anyway, Windows packaging is more important from my perspective and seems to see some progress lately (to which, unfortunately, I can't contribute due to lack of sufficient privileges on my work machine).

**Comment by aqeeliz** [comment]
I have previously thought about re-writing zim in QT, more of as a way to learn QT then any actual issue, but this isn't a small project, and the amount of time and effort needed to get it to the level zim currently is, isn't going to be small.

BTW, not a solution, but if you are stuck using Windows, and can't figure out a way to compile zim for the machine, there are quite a few alternatives available for it. Some are windows based, some are node-based, which can both run as a desktop or web app, and so on. Some of these are pretty good too, so worth checking out if you are stuck in such a position.

**Comment by fmos** [comment]
I eventually gave up when I found out that there is no compatible `string` type supported by both, Qt and Boost Spirit X3. At the same time the python bindings for Gtk seem to have progressed and now I was able to get Windows deployment to work (see #639 ). No further progress is to be expected on this issue from my side, therefore I close it.
